bank_project/bank_app/urls.py
from django.urls import path

from bank_app import views

app_name='bank'
urlpatterns=[
    path('',views.home,name='home'),
    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout,name='logout'),
    path('form/',views.finaltask,name='finaltask'),
path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),

]

bank_project/bank_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('bank_app.urls')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bank_project/bank_app/models.py
import uuid

from django.db import models
from multiselectfield import MultiSelectField
from django.contrib.auth.models import User
# Create your models here.
from django.shortcuts import redirect

Choices=[
    ('Thiruvanathapuram','tvm'),
    ('Ernakulam','ekm'),
    ('Calicut','clt'),
    ('Thrissur','thr'),
    ('Kottayam','ktym')

]
class Branches(models.Model):
    name=models.CharField(max_length=100,unique=True,choices=Choices)
    slug=models.SlugField(max_length=100,unique=True)
    link=models.CharField(max_length=500,blank=True)
    class Meta:
        ordering=['name',]
        verbose_name='district'
        verbose_name_plural='districts'


    def __str__(self):
        return self.name
gender_choice=(
    ('Male','Male'),
    ('Female','Female'),
    ('Transgender','Transgender')
)

class City(models.Model):
    name=models.CharField(max_length=200,unique=True)
    slug=models.SlugField(max_length=199,unique=True)
    branch=models.ForeignKey(Branches,on_delete=models.CASCADE)
    def __str__(self):
        return self.name

account_choices=[
    ('Savings Account','Savings Account'),
    ('Current Account','Current Account')
]

mat_choices=[
    ("Credit Card",'Credit Card'),
    ('Debit Card','Debit Card'),
    ('Pass Book','Pass Book')
]



class Task(models.Model):
    name=models.CharField(max_length=100,unique=True)
    slug=models.SlugField(max_length=100,default=uuid.uuid1)
    dob=models.DateField(blank=True)
    age=models.IntegerField(blank=True)
    gender=models.CharField(max_length=30,choices=gender_choice)
    phonenumber=models.IntegerField(blank=True)
    mailid=models.EmailField(max_length=300,blank=True)
    address=models.TextField(max_length=200,blank=True)
    district=models.ForeignKey(Branches,on_delete=models.CASCADE)
    city=models.ForeignKey(City,on_delete=models.CASCADE)
    account=models.CharField(max_length=200,choices=account_choices)
    material=MultiSelectField(choices=mat_choices)

    class Meta:
        ordering=['name',]
        verbose_name='task'
        verbose_name_plural='tasks'

    def __str(self):
        return  self.name


class Student(models.Model):
    first_name = models.CharField(max_length=20)
    last_name  = models.CharField(max_length=30)
    class Meta:
        db_table = "student"

bank_project/bank_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms
from .models import  Task, City,Student


class CustomUserForm(UserCreationForm):

    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control my-2', 'placeholder': 'Enter Username'}))
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control my-2', 'placeholder': 'Enter password'}))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control my-2 border-3', 'placeholder': 'Confirm password'}))

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

Choices=[
    ('CreditCard','CreditCard'),
    ('DebitCard','DebitCard'),
    ('PassBook','PassBook')
]
class TaskForm(forms.ModelForm):
    gender_choice = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Transgender', 'Transgender')
    )
    name = forms.CharField(widget=forms.TextInput(attrs={'style': 'width:50%;height:1.5rem;margin:1rem;'}))
    dob = forms.DateField(widget=forms.DateInput(attrs={'style': 'width:50%;height:1.5rem;margin:1rem;','type':'date'}))
    age=forms.IntegerField(widget=forms.NumberInput(attrs={'style': 'width:50%;height:1.5rem;margin:1rem;','type':'number'}))

    class Meta:
        model = Task
        # fields = "__all__"
        exclude = ('slug',)



    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'district' in self.data:
            try:
                branch_id = int(self.data.get('district'))
                self.fields['city'].queryset = City.objects.filter(branch_id=branch_id)
                    # .order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.branch.city_set.order_by('name')



    # def post(self):
    #     self.fields['material'] = self.request.POST.getall('mat')

    # def __init__(self, *args, **kwargs):
    #     super(TaskForm, self).__init__(*args, **kwargs)
    #     # self.fields['material'].widget = forms.CheckboxSelectMultiple(
    #     #     queryset=Material.objects.all(),
    #     #     widget=forms.CheckboxSelectMultiple,
    #     # )



class EmpForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"

bank_project/bank_app/views.py
from django.shortcuts import render, redirect
from .models import City,Branches
from django.contrib import auth, messages
from django.contrib.auth import authenticate
from .forms import CustomUserForm,TaskForm



def home(request):
    return render(request, 'index.html')


# Create your views here.
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/home/form/')
        else:
            messages.info(request, 'Invalid login')
            return redirect('/home/login/')
    return render(request, 'login.html')


def register(request):
    form = CustomUserForm()
    if request.method == 'POST':
        form = CustomUserForm(request.POST)
        if form.is_valid():
            # User.objects.create(**form.cleaned_data)
            form.save()
            messages.info(request, 'usercreated')
            print('user created')
            return redirect('/home/login/')

    return render(request, 'user_creation.html', {'form': form})


def logout(request):
    auth.logout(request)
    return redirect('/home/')


def finaltask(request):
    form = TaskForm()

    print(request)
    if request.method == 'POST':
        form = TaskForm(request.POST,request.FILES)
        f=request.POST.get('material')
        print(f)

        if form.is_valid():

            form.save()
            print('form saved')
            messages.success(request, 'Application Accepted.')
            return render(request,'final.html',{'form':form.cleaned_data})
        else:
            print(form.errors)

    return render(request,'final_form.html',{'form':form})
    #

def load_cities(request):
    branch_id = request.GET.get('branch_id')
    print(branch_id)
    cities = City.objects.filter(branch_id=branch_id)
    return render(request,'city_dropdown_list_options.html', {'cities': cities})

bank_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

     <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/js/bootstrap.min.js">

    {% block head %}{% endblock %}
</head>
<body>
{% include 'navbar.html' %}
{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>

<script src="{% static 'js/bootstrap.bundle.min.js' %}" ></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>

</body>
</html>

bank_project/templates/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

bank_project/templates/final.html
{% extends 'base.html' %}
{% block title %}
Form
{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12 col-md-12 col-lg-12 text-center">
            <h1>Last Page</h1>
            <div class="card" style="width:100%;">

                <div class="card-body">


                    <div style="display:flex;" class="form-group">
                        <div class="p-2 mt-2" style="width:25%;"><p>Name</p></div>
                        <div class="p-2 mt-2 ml-2" style="width:65%;"></div>
                        {{form.name}}
                    </div>

                    <div style="display:flex;" class="form-group">
                        <div class="p-2 mt-2" style="width:25%;"><p>Date of Birth</p></div>
                        <div class="p-2 mt-2 ml-2" style="width:65%;"></div>
                        {{form.address}}
                    </div>

                    <div style="display:flex;" class="form-group">
                        <div class="p-2 mt-2" style="width:25%;"><p>Age</p></div>
                        <div class="p-2 mt-2 ml-2" style="width:65%;"></div>
                        {{form.age}}
                    </div>

                    <div style="display:flex;" class="form-group">
                        <div class="p-2 mt-2" style="width:25%;"><p>Gender</p></div>
                        <div class="p-2 mt-2 ml-2" style="width:65%;"></div>
                        {{form.gender}}
                    </div>

                    <div style="display:flex;" class="form-group">
                        <div class="p-2 mt-2" style="width:25%;"><p>Phone Number</p></div>
                        <div class="p-2 mt-2 ml-2" style="width:65%;"></div>
                        {{form.phonenumber}}
                    </div>

                    <div style="display:flex;" class="form-group">
                        <div class="p-2 mt-2" style="width:25%;"><p>Address</p></div>
                        <div class="p-2 mt-2 ml-2" style="width:65%;"></div>
                        {{form.mailid}}
                    </div>


                    <div style="display:flex;" class="form-group">
                        <div class="p-2 mt-2" style="width:25%;"><p>Address</p></div>
                        <div class="p-2 mt-2 ml-2" style="width:65%;"></div>
                        {{form.address}}
                    </div>


                    <div style="display:flex;" class="form-group">
                        <div class="p-2 mt-2" style="width:25%;"><p>District</p></div>
                        <div class="p-2 mt-2 ml-2" style="width:65%;"></div>
                        {{form.district}}
                    </div>

                    <div style="display:flex;" class="form-group">
                        <div class="p-2 mt-2" style="width:25%;"><p>City</p></div>
                        <div class="p-2 mt-2 ml-2" style="width:65%;"></div>
                        {{form.city}}
                    </div>


                    <div style="display:flex;" class="form-group">
                        <div class="p-2 mt-2" style="width:25%;"><p> Account</p></div>
                        <div class="p-2 mt-2 ml-2" style="width:65%;"></div>
                        {{form.account}}
                    </div>

                    <div style="display:flex;" class="form-group">
                        <div class="p-2 mt-2" style="width:25%;"><p>Material</p></div>
                        <div class="p-2 mt-2 ml-2" style="width:65%;"></div>
                        {{form.material}}
                    </div>




                    <a href="{% url 'bank:home' %}" class="btn btn-primary mb-5">Home</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

bank_project/templates/final_form.html
{% extends 'base.html' %}
{% block title %}
Form
{% endblock %}
{% block head %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
    $(document).ready(function(){
    $("#btshow").click(function(){
    $("#myDiv").css("display","block");
    });
    });

</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
   $(document).ready(function()
    {
     $('.mat').click(function()
     {
    var txt="";
    $('.mat:checked').each(function()
    {
    txt+=$(this).val()+","
    });
    $('#txtvalues').val(txt);
    });
    });

</script>


{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 text-center mt-5">


            <button id="btshow" class="btn btn-primary mt-3 mb-4">click to show form</button>
            <div id="myDiv" style="display:none;border-style:solid;">


                <form class="form mt-4" method='POST' data-cities-url="{% url 'bank:ajax_load_cities' %}"
                      enctype="multipart/form-data" id="personForm">
                    {% csrf_token %}
                    {% if messages %}
                    {% for i in messages %}
                    {{form.errors}}


                    <p class="h4"> {{i}}</p>
                    {% endfor %}
                    {% endif %}

                    <br>
                    <button type='submit' class="btn btn-danger mt-1 mt-3" value='submit' id="btn1">
                        Submit
                    </button>

                    {% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}

                </form>




            </div>
            <br>
            <a href="{% url 'bank:home' %}" class="btn btn-primary mb-5 mt-5">Home</a>


        </div>
    </div>
</div>


<!--<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>-->
<script>
    $("#id_district").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const districtId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'branch_id': districtId       // add the country id to the GET parameters
            },
            success: function (data) {
               console.log(data)
               // `data` is the return of the `load_cities` view function
                $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });

    });

</script>


{% endblock %}


<!--                    <div style="display:flex;" class="form-group">-->
<!--                        <div class="p-2 mt-2" style="width:25%;">-->
<!--                            <p> Username</p>-->
<!--                        </div>-->
<!--                        <div class="p-2 mt-2 ml-2" style="width:65%;">-->
<!--                          <input type="text" name="username" placeholder="Enter the name" style="width:100%;">-->
<!--                        </div>-->
<!--                    </div>-->

<!--                     <div style="display:flex;" class="form-group">-->
<!--                        <div class="p-2 mt-2" style="width:25%;">-->
<!--                            <p> Date of Birth</p>-->
<!--                        </div>-->
<!--                        <div class="p-2 mt-2 ml-2" style="width:65%;">-->
<!--                          <input type="date" name="dob" placeholder="Enter the date of birth" style="width:100%;">-->
<!--                        </div>-->
<!--                    </div>-->

<!--                     <div style="display:flex;" class="form-group">-->
<!--                        <div class="p-2 mt-2" style="width:25%;">-->
<!--                            <p> Age</p>-->
<!--                        </div>-->
<!--                        <div class="p-2 mt-2 ml-2" style="width:65%;">-->
<!--                          <input type="number" name="age" placeholder="Enter the age" style="width:100%;">-->
<!--                        </div>-->
<!--                    </div>-->

<!--                     <div style="display:flex;" class="form-group">-->
<!--                        <div class="p-2 mt-2" style="width:25%;">-->
<!--                            <p> gender</p>-->
<!--                        </div>-->
<!--                        <div class="p-2 mt-2 ml-2" style="width:65%;">-->
<!--                          <input type="text" name="gender" placeholder="Enter the name" style="width:100%;">-->
<!--                        </div>-->
<!--                    </div>-->
<!--                     <div style="display:flex;" class="form-group">-->
<!--                        <div class="p-2 mt-2" style="width:25%;">-->
<!--                            <p>Phone Number</p>-->
<!--                        </div>-->
<!--                        <div class="p-2 mt-2 ml-2" style="width:65%;">-->
<!--                          <input type="number" name="phonenumber" placeholder="Enter the phone number" style="width:100%;">-->
<!--                        </div>-->
<!--                    </div>-->

<!--                     <div style="display:flex;" class="form-group">-->
<!--                        <div class="p-2 mt-2" style="width:25%;">-->
<!--                            <p>Email id</p>-->
<!--                        </div>-->
<!--                        <div class="p-2 mt-2 ml-2" style="width:65%;">-->
<!--                          <input type="email" name="mailid" placeholder="Enter the Email" style="width:100%;">-->
<!--                        </div>-->
<!--                    </div>-->

<!--                     <div style="display:flex;" class="form-group">-->
<!--                        <div class="p-2 mt-2" style="width:25%;">-->
<!--                            <p>Address</p>-->
<!--                        </div>-->
<!--                        <div class="p-2 mt-2 ml-2" style="width:65%;">-->
<!--                            <textarea rows="5" name="address" placeholder="Enter the name" style="width:100%;"></textarea>-->
<!--                        </div>-->
<!--                    </div>-->

<!--                     <div style="display:flex;" class="form-group">-->
<!--                        <div class="p-2 mt-2" style="width:25%;">-->
<!--                            <p>District</p>-->
<!--                        </div>-->
<!--                        <div class="p-2 mt-2 ml-2" style="width:65%;">-->
<!--                          <input type="text" name="district" placeholder="Select the District" style="width:100%;">-->
<!--                        </div>-->
<!--                    </div>-->

<!--                     <div style="display:flex;" class="form-group">-->
<!--                        <div class="p-2 mt-2" style="width:25%;">-->
<!--                            <p>City</p>-->
<!--                        </div>-->
<!--                        <div class="p-2 mt-2 ml-2" style="width:65%;">-->
<!--                          <input type="text" name="city" placeholder="Select the city" style="width:100%;">-->
<!--                        </div>-->
<!--                    </div>-->

<!--                     <div style="display:flex;" class="form-group">-->
<!--                        <div class="p-2 mt-2" style="width:25%;">-->
<!--                            <p> Account</p>-->
<!--                        </div>-->
<!--                        <div class="p-2 mt-2 ml-2" style="width:65%;">-->

<!--                          <input type="text" name="username" placeholder="Enter the name" style="width:100%;" value="{{form.account}}">-->

<!--                        </div>-->
<!--                    </div>-->

<!--                     <div style="display:flex;" class="form-group">-->
<!--                        <div class="p-2 mt-2" style="width:25%;">-->
<!--                            <p> Material</p>-->
<!--                        </div>-->
<!--                        <div class="p-2 mt-2 ml-2" style="width:65%;">-->
<!--                          <input type="checkbox" value="CreditCard" name="mat">Credit Card-->
<!--                          <input type="checkbox" value="DebitCard" name="mat">Debit Card-->
<!--                          <input type="checkbox" value="PassBook" name="mat">Passbook-->
<!--                          <input type="text" name="" id="txtvalues">-->
<!--                        </div>-->
<!--                    </div>-->

                    <!--    <p>Materials :</p>-->

bank_project/templates/login.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 text-center">
            <div class="text-center" >
                <div style="width:50%;margin-left:25%;background:white;" class="border rounded-3 p-5 mt-3">
<h2 class="mt-3 font-weight-bold tx_color" >Sign Up</h2>



                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputUser"></label>
                        <input type="text" name="username" class="form-control" id="exampleInputUser"
                               aria-describedby="emailHelp" placeholder="Enter Username">

                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1"></label>
                        <input type="password" name="password" class="form-control" id="exampleInputPassword1"
                               placeholder="Password">
                    </div>
                    <div>
                    <div class="text-start">
                        <button type="submit" class="btn btn-primary mt-3">Sign in</button>
                    </div>
                    <div class="text-end">
                        <a href="{% url 'bank:register' %}" class="btn btn-primary mt-3">Register</a>
                    </div></div>
                </form>

<div class="alert alert-danger mt-5" role="alert">
                    {% for i in messages %}
                    {{i}}
                    {% endfor %}
                </div>
            </div>
                </div>
        </div>

    </div>
</div>


{% endblock %}

bank_project/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bd_color">
  <a class=" col-lg-3 navbar-brand wh" href="">
    Dan Bank
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">


      <div class="col-lg-5" style="display:flex;margin-left:15rem;">
<ul class="navbar-nav mx-auto ">
      <li class="nav-item active">
        <a class="nav-link wh" href="{% url 'bank:home' %}" >Home </a>
      </li>
    {% if request.user.is_authenticated %}

    <li class="nav-item dropdown" >
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-bs-toggle="dropdown"  aria-expanded="false">
          {{user}}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">


          <a class="dropdown-item" href="{% url 'bank:logout' %}">Logout</a>

        </div>
    {% else %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'bank:login' %}" >Login</a>
      </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'bank:register' %}" >Register</a>
      </li>

    {% endif %}



<!--      <li class="nav-item dropdown {% if '' in request.path %}active{% endif %}" >-->
<!--        <a class="nav-link dropdown-toggle" href="#" id="anavbarDropdown" role="button" data-bs-toggle="dropdown"  aria-expanded="false" >-->
<!--          Branches-->
<!--        </a>-->
<!--        <ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:yellow;">-->
<!--             {% for branch in links %}-->

<!--          <li><a class="dropdown-item" href="" style="color:black;font-size:1.1rem;">{{link.name}}</a></li>-->
<!--                {% endfor %}-->

<!--        </ul>-->
<!--      </li>-->


     <li class="nav-item dropdown {% if '' in request.path %}active{% endif %}">
                    <a class="nav-link dropdown-toggle wh" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown"  aria-expanded="false" style="font-weight:650;font-size:1rem;">
                        Districts
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:yellow;">



                        {% for branch in links %}
                        <li><a class="dropdown-item " href="{{branch.link}}">{{branch.name}} </a></li>
                        {% endfor %}

                    </ul>
                </li>



    </ul>
</div>


  </div>
</nav>

bank_project/templates/user_creation.html
{% extends 'base.html' %}

{% block title %}
Register
{% endblock %}
{% block content %}


<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 text-center">
            <div class="text-center" >
                <div style="width:50%;margin-left:25%;background:white;" class="border rounded-3 p-5 mt-3">
<h2 class="mt-3 font-weight-bold tx_color mb-5" >Register</h2>



                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="form-group">

                        {{form.username}}
                        {% if form.errors.username %}
                        <label class="text-danger">
                            {{form.errors.username}}

                        </label>
                        {% endif %}
                    </div>

                    <div class="form-group">

                        {{form.password1}}
                        {% if form.errors.password1 %}
                        <label class="text-danger">
                            {{form.errors.password1}}

                        </label>
                        {% endif %}
                    </div>
                    <div class="form-group">

                        {{form.password2}}
                        {% if form.errors.password2 %}
                        <label class="text-danger">
                            {{form.errors.password2}}

                        </label>
                        {% endif %}
                    </div>

                    <div class="text-end">
                        <button type="submit" class="btn btn-success mt-3" value="submit">Create Account</button>
                    </div>
                </form>
<div class="alert alert-danger mt-5" role="alert">
                    {% for i in messages %}
                    {{i}}
                    {% endfor %}
                </div>

            </div>
                </div>
        </div>
    </div>
</div>



{% endblock %}